#!/bin/bash

echo "Removing all test files ..."
rm -rf ./2dcontext
rm -rf ./accelerometer
rm -rf ./accname
rm -rf ./acid
rm -rf ./ambient-light
rm -rf ./animation-worklet
rm -rf ./annotation-model
rm -rf ./annotation-protocol
rm -rf ./annotation-vocab
rm -rf ./apng
rm -rf ./appmanifest
rm -rf ./async-local-storage
rm -rf ./audio-output
rm -rf ./background-fetch
rm -rf ./BackgroundSync
rm -rf ./badging
rm -rf ./battery-status
rm -rf ./beacon
rm -rf ./bluetooth
rm -rf ./clear-site-data
rm -rf ./client-hints
rm -rf ./clipboard-apis
rm -rf ./compat
rm -rf ./compression
rm -rf ./conformance-checkers
rm -rf ./console
rm -rf ./content-dpr
rm -rf ./content-security-policy
rm -rf ./contenteditable
rm -rf ./cookies
rm -rf ./cookie-store
rm -rf ./core-aam
rm -rf ./cors
rm -rf ./credential-management
rm -rf ./css
rm -rf ./custom-elements
rm -rf ./delegated-ink
rm -rf ./device-memory
rm -rf ./document-policy
rm -rf ./dom
rm -rf ./domparsing
rm -rf ./domxpath
rm -rf ./dpctf
rm -rf ./dpub-aam
rm -rf ./dpub-aria
rm -rf ./editing
rm -rf ./element-timing
rm -rf ./encoding
rm -rf ./encoding-detection
rm -rf ./encrypted-media
rm -rf ./entries-api
rm -rf ./eventsource
rm -rf ./event-timing
rm -rf ./feature-policy
rm -rf ./fetch
rm -rf ./FileAPI
rm -rf ./forced-colors-mode
rm -rf ./fullscreen
rm -rf ./gamepad
rm -rf ./generic-sensor
rm -rf ./geolocation-API
rm -rf ./geolocation-sensor
rm -rf ./graphics-aam
rm -rf ./gyroscope
rm -rf ./hit-test
rm -rf ./hr-time
rm -rf ./html
rm -rf ./html-longdesc
rm -rf ./html-media-capture
rm -rf ./idle-detection
rm -rf ./imagebitmap-renderingcontext
rm -rf ./import-maps
rm -rf ./IndexedDB
rm -rf ./inert
rm -rf ./infrastructure
rm -rf ./input-device-capabilities
rm -rf ./input-events
rm -rf ./intersection-observer
rm -rf ./js
rm -rf ./js-self-profiling
rm -rf ./keyboard-lock
rm -rf ./keyboard-map
rm -rf ./largest-contentful-paint
rm -rf ./layout-instability
rm -rf ./lifecycle
rm -rf ./loading
rm -rf ./longtask-timing
rm -rf ./magnetometer
rm -rf ./manifest
rm -rf ./mathml
rm -rf ./media-capabilities
rm -rf ./mediacapture-depth
rm -rf ./mediacapture-fromelement
rm -rf ./mediacapture-image
rm -rf ./mediacapture-record
rm -rf ./mediacapture-streams
rm -rf ./mediasession
rm -rf ./media-source
rm -rf ./mimesniff
rm -rf ./mixed-content
rm -rf ./mst-content-hint
rm -rf ./native-file-system
rm -rf ./native-io
rm -rf ./navigation-timing
rm -rf ./netinfo
rm -rf ./network-error-logging
rm -rf ./notifications
rm -rf ./offscreen-canvas
rm -rf ./old-tests
rm -rf ./orientation-event
rm -rf ./orientation-sensor
rm -rf ./origin-isolation
rm -rf ./origin-policy
rm -rf ./page-lifecycle
rm -rf ./page-visibility
rm -rf ./paint-timing
rm -rf ./payment-handler
rm -rf ./payment-method-basic-card
rm -rf ./payment-method-id
rm -rf ./payment-request
rm -rf ./performance-timeline
rm -rf ./PeriodicBackgroundSync
rm -rf ./periodic-background-sync
rm -rf ./permissions
rm -rf ./permissions-request
rm -rf ./permissions-revoke
rm -rf ./picture-in-picture
rm -rf ./pointerevents
rm -rf ./pointerlock
rm -rf ./portals
rm -rf ./preload
rm -rf ./presentation-api
rm -rf ./printing
rm -rf ./priority-hints
rm -rf ./proximity
rm -rf ./push-api
rm -rf ./quirks
rm -rf ./referrer-policy
rm -rf ./remote-playback
rm -rf ./reporting
rm -rf ./requestidlecallback
rm -rf ./resize-observer
rm -rf ./resource-timing
rm -rf ./screen-capture
rm -rf ./screen_enumeration
rm -rf ./screen-orientation
rm -rf ./screen-wake-lock
rm -rf ./scroll-animations
rm -rf ./scroll-to-text-fragment
rm -rf ./secure-contexts
rm -rf ./selection
rm -rf ./serial
rm -rf ./server-timing
rm -rf ./service-workers
rm -rf ./shadow-dom
rm -rf ./shape-detection
rm -rf ./signed-exchange
rm -rf ./sms
rm -rf ./speech-api
rm -rf ./storage
rm -rf ./streams
rm -rf ./subresource-integrity
rm -rf ./svg
rm -rf ./svg-aam
rm -rf ./timing-entrytypes-registry
rm -rf ./touch-events
rm -rf ./trust-tokens
rm -rf ./trusted-types
rm -rf ./uievents
rm -rf ./upgrade-insecure-requests
rm -rf ./url
rm -rf ./user-timing
rm -rf ./vibration
rm -rf ./video-raf
rm -rf ./video-rvfc
rm -rf ./visual-viewport
rm -rf ./wai-aria
rm -rf ./wake-lock
rm -rf ./wasm
rm -rf ./web-animations
rm -rf ./web-bundle
rm -rf ./webaudio
rm -rf ./webauthn
rm -rf ./WebCryptoAPI
rm -rf ./webdriver
rm -rf ./webgl
rm -rf ./webgpu
rm -rf ./wave-extra
rm -rf ./WebIDL
rm -rf ./web-locks
rm -rf ./webmessaging
rm -rf ./webmidi
rm -rf ./web-nfc
rm -rf ./webrtc
rm -rf ./webrtc-extensions
rm -rf ./webrtc-identity
rm -rf ./webrtc-insertable-streams
rm -rf ./webrtc-priority
rm -rf ./webrtc-quic
rm -rf ./webrtc-stats
rm -rf ./webrtc-svc
rm -rf ./web-share
rm -rf ./websockets
rm -rf ./webstorage
rm -rf ./webtransport
rm -rf ./webusb
rm -rf ./webvr
rm -rf ./webvtt
rm -rf ./webxr
rm -rf ./workers
rm -rf ./worklets
rm -rf ./x-frame-options
rm -rf ./xhr
